class AnimalData {
  static Map<String, List<String>> categoryWordBank = {
    "Animal": [

      "ALPACA", "ANTEATER", "ARMADILLO", "BADGER", "BAT", "BEAR", "BEAVER", "BISON", "BUFFALO", "CAMEL",
      "CARIBOU", "CAT", "CHEETAH", "CHIMPANZEE", "CHIPMUNK", "COW", "COYOTE", "DEER", "DOG", "DOLPHIN",
      "DONKEY",  "ELEPHANT", "FERRET", "FOX", "FROG", "GERBIL", "GIRAFFE", "GOAT",
      "GOPHER", "GORILLA", "GUINEA_PIG", "HAMSTER", "HARE", "HEDGEHOG", "HIPPOPOTAMUS", "HORSE", "HYENA",
      "IBEX", "JAGUAR", "KANGAROO", "KOALA", "LEMUR", "LEOPARD", "LION", "LLAMA", "LYNX",
      "MANATEE", "MEERKAT", "MINK", "MOLE", "MONGOOSE", "MONKEY", "MOUSE", "MULE", "MUSKRAT", "OCELOT",
       "OPOSSUM", "ORANGUTAN", "OTTER", "PANDA", "PIG", "PLATYPUS", "PORCUPINE",
      "POSSUM", "PRONGHORN", "RABBIT", "RAT", "RHINOCEROS", "SEAL", "SERVAL", "SHEEP", "SKUNK", "SLOTH",
      "TAPIR", "TASMANIAN_DEVIL", "TIGER",  "WALRUS", "WEASEL", "WHALE", "WILDCAT",
      "WOLF", "ZEBRA"
    ]
  };

  static Map<String, String> imageMapping = {
    "ALPACA": "assets/images/animal/ALPACA.jpg",
    "ANTEATER": "assets/images/animal/ANTEATER.jpg",
    "ARMADILLO": "assets/images/animal/ARMADILLO.jpg",
    "BADGER": "assets/images/animal/BADGER.jpg",
    "BAT": "assets/images/animal/BAT.jpg",
    "BEAR": "assets/images/animal/BEAR.jpg",
    "BEAVER": "assets/images/animal/BEAVER.jpg",
    "BISON": "assets/images/animal/BISON.jpg",
    "BUFFALO": "assets/images/animal/BUFFALO.jpg",
    "CAMEL": "assets/images/animal/CAMEL.jpg",
    "CARIBOU": "assets/images/animal/CARIBOU.jpg",
    "CAT": "assets/images/animal/CAT.jpg",
    "CHEETAH": "assets/images/animal/CHEETAH.jpg",
    "CHIMPANZEE": "assets/images/animal/CHIMPANZEE.jpg",
    "CHIPMUNK": "assets/images/animal/CHIPMUNK.jpg",
    "COW": "assets/images/animal/COW.jpg",
    "COYOTE": "assets/images/animal/COYOTE.jpg",
    "DEER": "assets/images/animal/DEER.jpg",
    "DOG": "assets/images/animal/DOG.jpg",
    "DOLPHIN": "assets/images/animal/DOLPHIN.jpg",
    "DONKEY": "assets/images/animal/DONKEY.jpg",
    "ELEPHANT": "assets/images/animal/ELEPHANT.jpg",
    "FERRET": "assets/images/animal/FERRET.jpg",
    "FOX": "assets/images/animal/FOX.jpg",
    "FROG": "assets/images/animal/FROG.jpg",
    "GERBIL": "assets/images/animal/GERBIL.jpg",
    "GIRAFFE": "assets/images/animal/GIRAFFE.jpg",
    "GOAT": "assets/images/animal/GOAT.jpg",
    "GOPHER": "assets/images/animal/GOPHER.jpg",
    "GORILLA": "assets/images/animal/GORILLA.jpg",
    "GUINEA_PIG": "assets/images/animal/GUINEA_PIG.jpg",
    "HAMSTER": "assets/images/animal/HAMSTER.jpg",
    "HARE": "assets/images/animal/HARE.jpg",
    "HEDGEHOG": "assets/images/animal/HEDGEHOG.jpg",
    "HIPPOPOTAMUS": "assets/images/animal/HIPPOPOTAMUS.jpg",
    "HORSE": "assets/images/animal/HORSE.jpg",
    "HYENA": "assets/images/animal/HYENA.jpg",
    "IBEX": "assets/images/animal/IBEX.jpg",
    "JAGUAR": "assets/images/animal/JAGUAR.jpg",
    "KANGAROO": "assets/images/animal/KANGAROO.jpg",
    "KOALA": "assets/images/animal/KOALA.jpg",
    "LEMUR": "assets/images/animal/LEMUR.jpg",
    "LEOPARD": "assets/images/animal/LEOPARD.jpg",
    "LION": "assets/images/animal/LION.jpg",
    "LLAMA": "assets/images/animal/LLAMA.jpg",
    "LYNX": "assets/images/animal/LYNX.jpg",
    "MANATEE": "assets/images/animal/MANATEE.jpg",
    "MEERKAT": "assets/images/animal/MEERKAT.jpg",
    "MINK": "assets/images/animal/MINK.jpg",
    "MOLE": "assets/images/animal/MOLE.jpg",
    "MONGOOSE": "assets/images/animal/MONGOOSE.jpg",
    "MONKEY": "assets/images/animal/MONKEY.jpg",
    "MOUSE": "assets/images/animal/MOUSE.jpg",
    "MULE": "assets/images/animal/MULE.jpg",
    "MUSKRAT": "assets/images/animal/MUSKRAT.jpg",
    "OCELOT": "assets/images/animal/OCELOT.jpg",
    "OPOSSUM": "assets/images/animal/OPOSSUM.jpg",
    "ORANGUTAN": "assets/images/animal/ORANGUTAN.jpg",
    "OTTER": "assets/images/animal/OTTER.jpg",
    "PANDA": "assets/images/animal/PANDA.jpg",

    "PIG": "assets/images/animal/PIG.jpg",
    "PLATYPUS": "assets/images/animal/PLATYPUS.jpg",
    "PORCUPINE": "assets/images/animal/PORCUPINE.jpg",
    "POSSUM": "assets/images/animal/POSSUM.jpg",
    "PRONGHORN": "assets/images/animal/PRONGHORN.jpg",
    "RABBIT": "assets/images/animal/RABBIT.jpg",
    "RAT": "assets/images/animal/RAT.jpg",
    "RHINOCEROS": "assets/images/animal/RHINOCEROS.jpg",
    "SEAL": "assets/images/animal/SEAL.jpg",
    "SERVAL": "assets/images/animal/SERVAL.jpg",
    "SHEEP": "assets/images/animal/SHEEP.jpg",
    "SKUNK": "assets/images/animal/SKUNK.jpg",
    "SLOTH": "assets/images/animal/SLOTH.jpg",
    "TAPIR": "assets/images/animal/TAPIR.jpg",
    "TASMANIAN_DEVIL": "assets/images/animal/TASMANIAN_DEVIL.jpg",
    "TIGER": "assets/images/animal/TIGER.jpg",

    "WALRUS": "assets/images/animal/WALRUS.jpg",
    "WEASEL": "assets/images/animal/WEASEL.jpg",
    "WHALE": "assets/images/animal/WHALE.jpg",
    "WILDCAT": "assets/images/animal/WILDCAT.jpg",
    "WOLF": "assets/images/animal/WOLF.jpg",
    "ZEBRA": "assets/images/animal/ZEBRA.jpg"
  };
}
