class FlowerData {
  static Map<String, List<String>> categoryWordBank = {
    "Flower": [
      "ALSTROEMERIA", "ALYSSUM", "ANEMONE", "ASTER", "AZALEA", "BELLFLOWER", "BLACK_EYED_SUSAN",
      "BLEEDING_HEART", "BLUEBELL", "BORAGE", "BUTTERCUP", "CALENDULA", "CAMELLIA", "CAMPANULA",
      "CANTERBURY_BELLS", "CARNATION", "CELOSIA", "CHERRY_BLOSSOM", "CHRYSANTHEMUM", "CLEMATIS",
      "COLUMBINE", "CONEFLOWER", "COREOPSIS", "CORNFLOWER", "COSMOS", "CROCUS", "DAFFODIL", "DAHLIA",
      "DAISY", "DANDELION", "DELPHINIUM", "EVENING_PRIMROSE", "FORGET_ME_NOT", "FOXGLOVE", "FREESIA",
      "GARDENIA", "GERANIUM", "GLADIOLUS", "HEATHER", "HIBISCUS", "HOLLYHOCK", "HONEYSUCKLE", "HYDRANGEA",
      "IRIS", "JASMINE", "LAVENDER", "LILY", "LOBELIA", "LOTUS", "LUPINE", "MAGNOLIA", "MARIGOLD",
      "NEMOPHILA", "ORCHID", "PANSY", "PEONY", "PETASITES", "PETUNIA", "PHLOX", "POPPY", "PRIMROSE",
      "RANUNCULUS", "ROSE", "SALVIA", "SCABIOSA", "SNAPDRAGON", "SPEEDWELL", "SPIREA", "STATICE",
      "SUNFLOWER", "SWEET_PEA", "THISTLE", "TOADFLAX", "TRILLIUM", "TULIP", "VERBENA", "VIBURNUM",
      "VIOLET", "WALLFLOWER", "WAXFLOWER", "WINDFLOWER", "WISTERIA", "YARROW", "ZINNIA"
    ]
  };

  static Map<String, String> imageMapping = {
    "ALSTROEMERIA": "assets/images/flower/ALSTROEMERIA.jpg",
    "ALYSSUM": "assets/images/flower/ALYSSUM.jpg",
    "ANEMONE": "assets/images/flower/ANEMONE.jpg",
    "ASTER": "assets/images/flower/ASTER.jpg",
    "AZALEA": "assets/images/flower/AZALEA.jpg",
    "BELLFLOWER": "assets/images/flower/BELLFLOWER.jpg",
    "BLACK_EYED_SUSAN": "assets/images/flower/BLACK_EYED_SUSAN.jpg",
    "BLEEDING_HEART": "assets/images/flower/BLEEDING_HEART.jpg",
    "BLUEBELL": "assets/images/flower/BLUEBELL.jpg",
    "BORAGE": "assets/images/flower/BORAGE.jpg",
    "BUTTERCUP": "assets/images/flower/BUTTERCUP.jpg",
    "CALENDULA": "assets/images/flower/CALENDULA.jpg",
    "CAMELLIA": "assets/images/flower/CAMELLIA.jpg",
    "CAMPANULA": "assets/images/flower/CAMPANULA.jpg",
    "CANTERBURY_BELLS": "assets/images/flower/CANTERBURY_BELLS.jpg",
    "CARNATION": "assets/images/flower/CARNATION.jpg",
    "CELOSIA": "assets/images/flower/CELOSIA.jpg",
    "CHERRY_BLOSSOM": "assets/images/flower/CHERRY_BLOSSOM.jpg",
    "CHRYSANTHEMUM": "assets/images/flower/CHRYSANTHEMUM.jpg",
    "CLEMATIS": "assets/images/flower/CLEMATIS.jpg",
    "COLUMBINE": "assets/images/flower/COLUMBINE.jpg",
    "CONEFLOWER": "assets/images/flower/CONEFLOWER.jpg",
    "COREOPSIS": "assets/images/flower/COREOPSIS.jpg",
    "CORNFLOWER": "assets/images/flower/CORNFLOWER.jpg",
    "COSMOS": "assets/images/flower/COSMOS.jpg",
    "CROCUS": "assets/images/flower/CROCUS.jpg",
    "DAFFODIL": "assets/images/flower/DAFFODIL.jpg",
    "DAHLIA": "assets/images/flower/DAHLIA.jpg",
    "DAISY": "assets/images/flower/DAISY.jpg",
    "DANDELION": "assets/images/flower/DANDELION.jpg",
    "DELPHINIUM": "assets/images/flower/DELPHINIUM.jpg",
    "EVENING_PRIMROSE": "assets/images/flower/EVENING_PRIMROSE.jpg",
    "FORGET_ME_NOT": "assets/images/flower/FORGET_ME_NOT.jpg",
    "FOXGLOVE": "assets/images/flower/FOXGLOVE.jpg",
    "FREESIA": "assets/images/flower/FREESIA.jpg",
    "GARDENIA": "assets/images/flower/GARDENIA.jpg",
    "GERANIUM": "assets/images/flower/GERANIUM.jpg",
    "GLADIOLUS": "assets/images/flower/GLADIOLUS.jpg",
    "HEATHER": "assets/images/flower/HEATHER.jpg",
    "HIBISCUS": "assets/images/flower/HIBISCUS.jpg",
    "HOLLYHOCK": "assets/images/flower/HOLLYHOCK.jpg",
    "HONEYSUCKLE": "assets/images/flower/HONEYSUCKLE.jpg",
    "HYDRANGEA": "assets/images/flower/HYDRANGEA.jpg",
    "IRIS": "assets/images/flower/IRIS.jpg",
    "JASMINE": "assets/images/flower/JASMINE.jpg",
    "LAVENDER": "assets/images/flower/LAVENDER.jpg",
    "LILY": "assets/images/flower/LILY.jpg",
    "LOBELIA": "assets/images/flower/LOBELIA.jpg",
    "LOTUS": "assets/images/flower/LOTUS.jpg",
    "LUPINE": "assets/images/flower/LUPINE.jpg",
    "MAGNOLIA": "assets/images/flower/MAGNOLIA.jpg",
    "MARIGOLD": "assets/images/flower/MARIGOLD.jpg",
    "NEMOPHILA": "assets/images/flower/NEMOPHILA.jpg",
    "ORCHID": "assets/images/flower/ORCHID.jpg",
    "PANSY": "assets/images/flower/PANSY.jpg",
    "PEONY": "assets/images/flower/PEONY.jpg",
    "PETASITES": "assets/images/flower/PETASITES.jpg",
    "PETUNIA": "assets/images/flower/PETUNIA.jpg",
    "PHLOX": "assets/images/flower/PHLOX.jpg",
    "POPPY": "assets/images/flower/POPPY.jpg",
    "PRIMROSE": "assets/images/flower/PRIMROSE.jpg",
    "RANUNCULUS": "assets/images/flower/RANUNCULUS.jpg",
    "ROSE": "assets/images/flower/ROSE.jpg",
    "SALVIA": "assets/images/flower/SALVIA.jpg",
    "SCABIOSA": "assets/images/flower/SCABIOSA.jpg",
    "SNAPDRAGON": "assets/images/flower/SNAPDRAGON.jpg",
    "SPEEDWELL": "assets/images/flower/SPEEDWELL.jpg",
    "SPIREA": "assets/images/flower/SPIREA.jpg",
    "STATICE": "assets/images/flower/STATICE.jpg",
    "SUNFLOWER": "assets/images/flower/SUNFLOWER.jpg",
    "SWEET_PEA": "assets/images/flower/SWEET_PEA.jpg",
    "THISTLE": "assets/images/flower/THISTLE.jpg",
    "TOADFLAX": "assets/images/flower/TOADFLAX.jpg",
    "TRILLIUM": "assets/images/flower/TRILLIUM.jpg",
    "TULIP": "assets/images/flower/TULIP.jpg",
    "VERBENA": "assets/images/flower/VERBENA.jpg",
    "VIBURNUM": "assets/images/flower/VIBURNUM.jpg",
    "VIOLET": "assets/images/flower/VIOLET.jpg",
    "WALLFLOWER": "assets/images/flower/WALLFLOWER.jpg",
    "WAXFLOWER": "assets/images/flower/WAXFLOWER.jpg",
    "WINDFLOWER": "assets/images/flower/WINDFLOWER.jpg",
    "WISTERIA": "assets/images/flower/WISTERIA.jpg",
    "YARROW": "assets/images/flower/YARROW.jpg",
    "ZINNIA": "assets/images/flower/ZINNIA.jpg"
  };
}
